spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/step2
    username: root
    password: 1234567890
    driverClassName: com.mysql.jdbc.Driver

  server:
    port: 8080